version: "3.7"

services:
  database:
    image: mysql:8.0
    build: images/mysql-ex
    platform: linux/amd64
    command:
      - "--default-authentication-plugin=mysql_native_password"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=codetest
      - MYSQL_USER=codetest
      - MYSQL_PASSWORD=swordfish
    ports:
      - "3306:3306"
    restart: always

  example-python:
    image: example-python
    build: images/example-python
    command : sh -c "sleep 10s ; python3 ./ingestor.py ; python3 ./report.py"
    volumes:
      - ./data:/data
    depends_on:
      - database